import { customization } from "./customization";

export const config = {
  ...customization,
  name: customization.brand.name,
  version: customization.version,
  logo: customization.brand.logo,
  logoMark: customization.brand.logoMark,
  appIcon: customization.brand.appIcon,
  baseUrl: customization.integrations.baseUrl,
  tagline: customization.brand.tagline,
  description: customization.brand.description,
  welcomeText: customization.brand.welcomeText,
  footerText: customization.brand.footerText,
  style: customization.style,
  styleId: customization.style.id,
  stylePreset: customization.style.preset,
  colorThemeId: customization.style.colorThemeId,
  colorTheme: customization.style.colorTheme,
  mapEnabled: customization.map.enabled,
  mapLabel: customization.map.label,
  mapImage: customization.map.image,
  defaultLocale: customization.limits.defaultLocale,
  articlesPerPage: customization.limits.articlesPerPage,
  maxUploadSize: customization.limits.maxUploadSize,
  registrationEnabled: customization.features.registrationEnabled,
  discussionsEnabled: customization.features.discussionsEnabled,
};
