export type CommandDestination = {
  id: string;
  label: string;
  href: string;
  group: string;
  keywords: string[];
  shortcut?: string;
  adminOnly?: boolean;
};

const FOCUSED_EXACT_PATHS = new Set(["/ask", "/graph", "/split", "/map", "/studio"]);
const FOCUSED_PREFIXES = ["/map/", "/present"];

export function isFocusedWorkspacePath(pathname: string): boolean {
  return (
    FOCUSED_EXACT_PATHS.has(pathname) ||
    FOCUSED_PREFIXES.some((prefix) => pathname.startsWith(prefix))
  );
}

export const COMMAND_DESTINATIONS: CommandDestination[] = [
  {
    id: "nav-home",
    label: "Home",
    href: "/",
    group: "Navigation",
    keywords: ["main", "page", "dashboard", "start"],
    shortcut: "G H",
  },
  {
    id: "nav-articles",
    label: "All Articles",
    href: "/articles",
    group: "Navigation",
    keywords: ["articles", "list", "browse"],
    shortcut: "G A",
  },
  {
    id: "nav-search",
    label: "Search",
    href: "/search",
    group: "Navigation",
    keywords: ["search", "find", "query"],
    shortcut: "G S",
  },
  {
    id: "nav-recent",
    label: "Recent Changes",
    href: "/recent-changes",
    group: "Navigation",
    keywords: ["recent", "changes", "history", "activity", "log"],
    shortcut: "G R",
  },
  {
    id: "nav-categories",
    label: "Categories",
    href: "/categories",
    group: "Navigation",
    keywords: ["categories", "topics", "sections"],
  },
  {
    id: "nav-tags",
    label: "Tags",
    href: "/tags",
    group: "Navigation",
    keywords: ["tags", "labels", "taxonomy"],
  },
  {
    id: "nav-graph",
    label: "Article Graph",
    href: "/graph",
    group: "Discovery",
    keywords: ["graph", "network", "visualization", "map", "connections"],
    shortcut: "G G",
  },
  {
    id: "nav-atlas",
    label: "Canon Atlas",
    href: "/atlas",
    group: "Discovery",
    keywords: ["atlas", "canon", "world", "map", "territories", "threads", "lore", "dossier", "wow"],
  },
  {
    id: "nav-trails",
    label: "Canon Trails",
    href: "/trails",
    group: "Discovery",
    keywords: ["trails", "routes", "reading", "path", "canon", "journey", "reader", "guided"],
  },
  {
    id: "nav-intelligence",
    label: "Knowledge Command Center",
    href: "/intelligence",
    group: "Discovery",
    keywords: ["intelligence", "command", "ops", "signals", "quality", "canon", "cockpit", "radar", "constellation", "simulator", "usp"],
  },
  {
    id: "nav-studio",
    label: "Arkivel Studio",
    href: "/studio",
    group: "Discovery",
    keywords: ["studio", "canvas", "bases", "board", "obsidian", "workspace", "json canvas", "publish", "operating system"],
  },
  {
    id: "nav-ask",
    label: "Ask My Wiki",
    href: "/ask",
    group: "Discovery",
    keywords: ["ask", "ai", "oracle", "assistant", "question"],
  },
  {
    id: "nav-health",
    label: "Wiki Health",
    href: "/health",
    group: "Discovery",
    keywords: ["health", "quality", "audit", "stubs", "broken links"],
  },
  {
    id: "nav-coverage",
    label: "Coverage Map",
    href: "/coverage",
    group: "Discovery",
    keywords: ["coverage", "gaps", "categories", "quality"],
  },
  {
    id: "nav-glossary",
    label: "Glossary",
    href: "/glossary",
    group: "Discovery",
    keywords: ["glossary", "terms", "definitions"],
  },
  {
    id: "nav-timeline",
    label: "Timeline",
    href: "/timeline",
    group: "Discovery",
    keywords: ["timeline", "chronology", "dates"],
  },
  {
    id: "nav-random",
    label: "Random Article",
    href: "/random",
    group: "Discovery",
    keywords: ["random", "surprise", "lucky"],
  },
  {
    id: "nav-tools",
    label: "All Tools",
    href: "/tools",
    group: "Navigation",
    keywords: ["tools", "directory", "everything", "more", "index"],
  },
  {
    id: "nav-popular",
    label: "Popular",
    href: "/popular",
    group: "Discovery",
    keywords: ["popular", "trending", "most read", "top"],
  },
  {
    id: "nav-explore",
    label: "Explore",
    href: "/explore",
    group: "Discovery",
    keywords: ["explore", "browse", "discover"],
  },
  {
    id: "nav-series",
    label: "Series",
    href: "/series",
    group: "Discovery",
    keywords: ["series", "sequence", "parts", "multi-part"],
  },
  {
    id: "nav-historical-timeline",
    label: "Historical Timeline",
    href: "/timeline/historical",
    group: "Discovery",
    keywords: ["historical", "timeline", "chronology", "in-world", "events"],
  },
  {
    id: "nav-digest",
    label: "Daily Digest",
    href: "/digest",
    group: "Discovery",
    keywords: ["digest", "daily", "summary", "changes"],
  },
  {
    id: "nav-activity",
    label: "Activity",
    href: "/activity",
    group: "Discovery",
    keywords: ["activity", "heatmap", "recent", "log"],
  },
  {
    id: "nav-discussions",
    label: "Discussions",
    href: "/discussions",
    group: "Discovery",
    keywords: ["discussions", "comments", "talk", "threads"],
  },
  {
    id: "nav-dashboard",
    label: "My Dashboard",
    href: "/dashboard",
    group: "Personal",
    keywords: ["dashboard", "widgets", "personal"],
  },
  {
    id: "nav-bookmarks",
    label: "Bookmarks",
    href: "/bookmarks",
    group: "Personal",
    keywords: ["bookmarks", "saved", "personal"],
  },
  {
    id: "nav-watchlist",
    label: "Watchlist",
    href: "/watchlist",
    group: "Personal",
    keywords: ["watchlist", "watch", "notifications"],
  },
  {
    id: "nav-reading-lists",
    label: "Reading Lists",
    href: "/reading-lists",
    group: "Personal",
    keywords: ["reading", "lists", "collections"],
  },
  {
    id: "nav-review",
    label: "Review Queue",
    href: "/review",
    group: "Personal",
    keywords: ["review", "queue", "spaced", "repetition"],
  },
  {
    id: "nav-canvas",
    label: "Canvas",
    href: "/canvas",
    group: "Personal",
    keywords: ["canvas", "board", "freeform", "json canvas"],
  },
  {
    id: "nav-whiteboards",
    label: "Whiteboards",
    href: "/whiteboards",
    group: "Personal",
    keywords: ["whiteboard", "sketch", "diagram", "draw"],
  },
  {
    id: "nav-scratchpad",
    label: "Scratchpad",
    href: "/scratchpad",
    group: "Personal",
    keywords: ["scratchpad", "scratch", "quick", "notes"],
  },
  {
    id: "nav-daily",
    label: "Daily Note",
    href: "/daily",
    group: "Personal",
    keywords: ["daily", "note", "journal", "today"],
  },
  {
    id: "nav-stats",
    label: "Wiki Stats",
    href: "/stats",
    group: "Discovery",
    keywords: ["stats", "statistics", "totals", "contributors", "numbers"],
  },
  {
    id: "nav-leaderboard",
    label: "Leaderboard",
    href: "/leaderboard",
    group: "Discovery",
    keywords: ["leaderboard", "contributors", "ranking", "top editors"],
  },
  {
    id: "nav-mentions",
    label: "Mentions",
    href: "/mentions",
    group: "Personal",
    keywords: ["mentions", "mentioned", "replies"],
  },
  {
    id: "nav-history",
    label: "Reading History",
    href: "/history",
    group: "Personal",
    keywords: ["history", "recently viewed", "reading"],
  },
  {
    id: "nav-flashcards",
    label: "Flashcards",
    href: "/flashcards",
    group: "Personal",
    keywords: ["flashcards", "study", "spaced repetition", "decks", "cards"],
  },
  {
    id: "nav-learning-paths",
    label: "Learning Paths",
    href: "/learning-paths",
    group: "Personal",
    keywords: ["learning", "paths", "courses", "curriculum"],
  },
  {
    id: "nav-til",
    label: "Today I Learned",
    href: "/til",
    group: "Personal",
    keywords: ["til", "today i learned", "learnings", "notes"],
  },
  {
    id: "nav-collections",
    label: "Smart Collections",
    href: "/collections",
    group: "Personal",
    keywords: ["collections", "smart", "saved", "rules"],
  },
  {
    id: "nav-change-requests",
    label: "Change Requests",
    href: "/change-requests",
    group: "Workspace",
    keywords: ["change requests", "proposals", "edits", "review"],
  },
  {
    id: "nav-reviews",
    label: "Review Requests",
    href: "/reviews",
    group: "Workspace",
    keywords: ["reviews", "review requests", "feedback"],
  },
  {
    id: "nav-forks",
    label: "Article Forks",
    href: "/forks",
    group: "Workspace",
    keywords: ["forks", "drafts", "variants", "merge"],
  },
  {
    id: "nav-bounties",
    label: "Bounties",
    href: "/bounties",
    group: "Workspace",
    keywords: ["bounties", "requests", "wanted articles"],
  },
  {
    id: "nav-compare",
    label: "Compare Revisions",
    href: "/compare",
    group: "Workspace",
    keywords: ["compare", "diff", "revisions", "versions"],
  },
  {
    id: "nav-split",
    label: "Split View",
    href: "/split",
    group: "Workspace",
    keywords: ["split", "side by side", "two articles"],
  },
  {
    id: "nav-export",
    label: "Export",
    href: "/export",
    group: "Workspace",
    keywords: ["export", "download", "markdown", "backup"],
  },
  {
    id: "nav-import",
    label: "Import",
    href: "/import",
    group: "Workspace",
    keywords: ["import", "obsidian", "notion", "migrate"],
  },
  {
    id: "nav-assets",
    label: "Asset Library",
    href: "/assets",
    group: "Workspace",
    keywords: ["assets", "images", "files", "uploads", "media"],
  },
  {
    id: "nav-help",
    label: "Help",
    href: "/help",
    group: "Reference",
    keywords: ["help", "documentation", "guide", "faq"],
  },
  {
    id: "nav-features",
    label: "Features",
    href: "/features",
    group: "Reference",
    keywords: ["features", "reference", "capabilities"],
  },
  {
    id: "nav-api-docs",
    label: "API Docs",
    href: "/api-docs",
    group: "Reference",
    keywords: ["api", "docs", "rest", "integration"],
  },
  {
    id: "admin-users",
    label: "Users",
    href: "/admin/users",
    group: "Admin",
    keywords: ["users", "accounts", "members", "roles"],
    adminOnly: true,
  },
  {
    id: "admin-metrics",
    label: "Metrics",
    href: "/admin/metrics",
    group: "Admin",
    keywords: ["metrics", "analytics", "performance", "monitoring"],
    adminOnly: true,
  },
  {
    id: "admin-search-analytics",
    label: "Search Analytics",
    href: "/admin/search-analytics",
    group: "Admin",
    keywords: ["search", "analytics", "queries", "zero results"],
    adminOnly: true,
  },
  {
    id: "admin-lint",
    label: "Lint Articles",
    href: "/admin/lint",
    group: "Admin",
    keywords: ["lint", "check", "validate", "quality"],
    adminOnly: true,
  },
  {
    id: "admin-plugins",
    label: "Plugins",
    href: "/admin/plugins",
    group: "Admin",
    keywords: ["plugins", "extensions", "modules"],
    adminOnly: true,
  },
  {
    id: "admin-webhooks",
    label: "Webhooks",
    href: "/admin/webhooks",
    group: "Admin",
    keywords: ["webhooks", "hooks", "integrations", "notifications"],
    adminOnly: true,
  },
];
