import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const categorySlug = searchParams.get("category");

  const where: Record<string, unknown> = { status: "published" };
  if (categorySlug) {
    where.category = { slug: categorySlug };
  }

  const articles = await prisma.article.findMany({
    where,
    orderBy: { title: "asc" },
    include: { category: true, tags: { include: { tag: true } } },
  });

  const wikiName = process.env.NEXT_PUBLIC_ARKIVEL_NAME || process.env.NEXT_PUBLIC_WIKI_NAME || "Arkivel";

  // Build TOC
  const tocItems = articles
    .map(
      (a, i) =>
        `<li><a href="#article-${a.slug}">${i + 1}. ${escapeHtml(a.title)}</a></li>`
    )
    .join("\n");

  // Build article sections
  const articleSections = articles
    .map((article) => {
      const tagNames = article.tags.map((at) => at.tag.name);
      const meta: string[] = [];
      if (article.category) {
        meta.push(`<strong>Category:</strong> ${escapeHtml(article.category.name)}`);
      }
      if (tagNames.length > 0) {
        meta.push(`<strong>Tags:</strong> ${escapeHtml(tagNames.join(", "))}`);
      }
      const metaHtml = meta.length
        ? `<p style="color:#54595d;font-size:0.85rem;margin-bottom:0.5rem;">${meta.join(" &middot; ")}</p>`
        : "";

      return `
    <article id="article-${article.slug}" style="page-break-before:always;margin-bottom:2rem;">
      <h2 style="font-family:'Linux Libertine',Georgia,serif;font-size:1.4rem;font-weight:400;border-bottom:1px solid #a2a9b1;padding-bottom:0.25rem;margin-top:1.5rem;">${escapeHtml(article.title)}</h2>
      ${metaHtml}
      <div class="wiki-content">${article.content}</div>
    </article>`;
    })
    .join("\n<hr>\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(wikiName)} Export</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #202122; line-height: 1.6; font-size: 14px; background: #fff; }
    h1 { font-family: 'Linux Libertine', Georgia, serif; font-size: 1.8rem; font-weight: 400; border-bottom: 1px solid #a2a9b1; padding-bottom: 0.3rem; }
    h2 { font-family: 'Linux Libertine', Georgia, serif; }
    a { color: #0645ad; text-decoration: none; }
    a:hover { text-decoration: underline; }
    hr { border: none; border-top: 1px solid #a2a9b1; margin: 1.5rem 0; }
    .toc { display: inline-block; border: 1px solid #a2a9b1; background: #f8f9fa; padding: 0.75rem 1.25rem; margin-bottom: 1.5rem; }
    .toc h3 { margin: 0 0 0.5rem; font-size: 0.95rem; text-align: center; }
    .toc ol { padding-left: 1.5rem; margin: 0; }
    .toc li { margin: 0.15rem 0; font-size: 0.85rem; }
    .wiki-content h1 { font-size: 1.3rem; border-bottom: 1px solid #a2a9b1; }
    .wiki-content h2 { font-size: 1.15rem; border-bottom: 1px solid #a2a9b1; }
    .wiki-content h3 { font-size: 1rem; font-weight: 700; }
    .wiki-content img { max-width: 100%; border: 1px solid #c8ccd1; }
    .wiki-content pre { background: #f8f9fa; border: 1px solid #c8ccd1; padding: 0.75rem; overflow-x: auto; font-size: 0.85em; }
    .wiki-content code { background: #f8f9fa; padding: 0.1rem 0.3rem; font-size: 0.875em; }
    .wiki-content pre code { background: none; padding: 0; }
    .wiki-content blockquote { border-left: 3px solid #c8ccd1; padding-left: 1rem; color: #54595d; font-style: italic; }
    .wiki-content table { border-collapse: collapse; width: 100%; margin: 0.5rem 0; }
    .wiki-content th, .wiki-content td { border: 1px solid #a2a9b1; padding: 0.35rem 0.5rem; text-align: left; font-size: 0.85rem; }
    .wiki-content th { background: #eaecf0; font-weight: 700; }
    .export-meta { color: #54595d; font-size: 0.85rem; margin-bottom: 1rem; }
    @media print { body { max-width: none; padding: 0; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(wikiName)} Export</h1>
  <p class="export-meta">Exported ${articles.length} article(s) on ${new Date().toISOString().split("T")[0]}${categorySlug ? ` &middot; Category: ${escapeHtml(categorySlug)}` : ""}</p>

  <div class="toc">
    <h3>Table of Contents</h3>
    <ol>
      ${tocItems}
    </ol>
  </div>

  <hr>

  ${articleSections}

  <hr>
  <p class="export-meta" style="text-align:center;">Generated by ${escapeHtml(wikiName)}</p>
</body>
</html>`;

  const filename = categorySlug
    ? `wiki-export-${categorySlug}.html`
    : "wiki-export.html";

  return new NextResponse(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export const dynamic = "force-dynamic";
